# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 18-647 Connected Embedded Systems Architecture Labs
email: joel.krebs@sv.cmu.edu
description: > # this means to ignore newlines until "baseurl:"
  Home of the labs for the course 18-647 on Connected Embedded Systems
  Architecture taught in Fall at Carnegie Mellon University in Silicon Valey.
host: "10.0.13.179"
github_username:  18647fs2015

# Build settings
markdown: kramdown
